void main() {
  String ilce = "Bayrampaşa";
  String kita = "Avrupa";
  String faks = "02121252533";
  int postaKodu = 34035;
  String instaAdresi = "asbdsad";
  String calistigiBolum = "departman";
  int urunMiktari = 5;
  String musteriSoyadi = "kılıc";
  double odemeMiktari = 64.45;
  String dogumTarihi = "17/11/1984";
  double borc = 24.50;
  bool medeniHal = true;
  String videoYorumu = "videoYorumu";
  String odemeSaati = "odemeSaati";
  double eftMiktari = 12.75;
  int satilanMiktar = 10;
  String telefonModeli = "telefonModeli";
  String dergiAdi = "dergiAdi";
  String basimTarihi = "2/10/2023";
  double zamMiktari = 0.3052;
  int daireSayisi = 12;
  double enlem = 12.17451;
  double boylam = 32.18566;
  String yemekAdi = "yemekAdi";
  double urunFiyati = 64.10;
  String sirket = "sirket";
  String videoAdi = "videoAdi";
  double muzikSuresi = 14.5;
  int mekanPuani = 4;
  String dosyaAdi = "dosyaAdi";
  String resimFormati = "resimformat";
  String renk = "kırmızı";
  String renkKodu = "0xff52525";
  String bilgisayarModeli = "deneme";
  double ekranBoyutu = 23.10;
  double kullanimSuresi = 32.45;
  int basinc = 35;
  int etkinlikGunu = 5;
  int odemeGunu = 10;
  String yolculukCikisTarihi = "7/3/2023";
  String mahalleAdi = "Altıntepsi";
  String otobusHatti = "32M";
  double kullanilanDakika = 12.50;
  int kargoTakipNo = 4568445648;
  int kuponSuresi = 2;
  int kuponKodu = 52;
  String faturaTarihi =  "12/5/2023";

  print("ilce :  $ilce");
  print("kita : $kita");
  print("faks : $faks");
  print("postaKodu : $postaKodu");
  print("instaAdresi : $instaAdresi");
  print("calistigiBolum : $calistigiBolum");
  print("urunMiktari : $urunMiktari");
  print("musteriSoyadi : $musteriSoyadi");
  print("odemeMiktari : $odemeMiktari");
  print("dogumTarihi : $dogumTarihi");
  print("borc : $borc");
  print("medeniHal : $medeniHal");
  print("videoYorumu : $videoYorumu");
  print("odemeSaati : $odemeSaati");
  print("eftMiktari : $eftMiktari");
  print("satilanMiktar : $satilanMiktar");
  print("telefonModeli : $telefonModeli");
  print("dergiAdi : $dergiAdi");
  print("basimTarihi : $basimTarihi");
  print("zamMiktari : $zamMiktari");
  print("daireSayisi : $daireSayisi");
  print("enlem : $enlem");
  print("boylam : $boylam");
  print("yemekAdi : $yemekAdi");
  print("urunFiyati : $urunFiyati");
  print("sirket : $sirket");
  print("videoAdi : $videoAdi");
  print("muzikSuresi : $muzikSuresi");
  print("mekanPuani : $mekanPuani");
  print("dosyaAdi : $dosyaAdi");
  print("resimFormati : $resimFormati");
  print("renk : $renk");
  print("renkKodu : $renkKodu");
  print("bilgisayarModeli : $bilgisayarModeli");
  print("ekranBoyutu : $ekranBoyutu");
  print("kullanimSuresi : $kullanimSuresi");
  print("basinc : $basinc");
  print("etkinlikGunu : $etkinlikGunu");
  print("odemeGunu : $odemeGunu");
  print("yolculukCikisTarihi : $yolculukCikisTarihi");
  print("mahalleAdi : $mahalleAdi");
  print("otobusHatti : $otobusHatti");
  print("kullanilanDakika : $kullanilanDakika");
  print("kargoTakipNo : $kargoTakipNo");
  print("kuponSuresi : $kuponSuresi");
  print("kuponKodu : $kuponKodu");
  print("faturaTarihi : $faturaTarihi");
}